### ISSUE TITLE
Support Node.js v14

### ISSUE THREAD

**Issue by jaydenseric** [mike-marcacci/fs-capacitor#28]
At the moment, the `graphql-upload` tests are failing for Node.js v14:

https://github.com/jaydenseric/graphql-upload/runs/701487224?check_suite_focus=true#step:4:82

The error is:

```
_stream_readable.js:636
  throw new ERR_METHOD_NOT_IMPLEMENTED('_read()');
  ^

Error [ERR_METHOD_NOT_IMPLEMENTED]: The _read() method is not implemented
    at Readable._read (_stream_readable.js:636:9)
    at Readable.read (_stream_readable.js:475:10)
    at resume_ (_stream_readable.js:962:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ERR_METHOD_NOT_IMPLEMENTED'
}
```

Is it because of this in `fs-capacitor`?:

https://github.com/mike-marcacci/fs-capacitor/blob/45ab8cb354a90914ce87c0069273ff40ff20654e/src/index.ts#L28

Does it relate to this Node.js v14 change?:

https://github.com/nodejs/node/pull/31912

Here are the Node.js v14 release notes:

https://nodejs.org/en/blog/release/v14.0.0/

**Comment by jaydenseric** [comment]
Apologies 🙏

The issue was in the `graphql-upload` tests:

https://github.com/jaydenseric/graphql-upload/commit/fa758f4f61fedb427c4f93179f19289e8c072f53
